# Generated by Django 2.1.5 on 2019-02-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
