# Generated by Django 2.1.5 on 2019-02-12 04:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('questions', models.ManyToManyField(to='polls.Question', verbose_name='Questions')),
            ],
        ),
    ]
