# Generated by Django 2.1.5 on 2019-02-13 04:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_quizsessions_current_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400)),
                ('hero_class', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('base_charateristics', django.contrib.postgres.fields.jsonb.JSONField(default={'attack': 0, 'defense': 0, 'knowledge': 0, 'spell_power': 0})),
                ('base_spells', models.CharField(max_length=20)),
                ('has_spellbook', models.BooleanField()),
                ('portrait', models.FileField(upload_to='')),
            ],
        ),
    ]
