# Generated by Django 2.1.5 on 2019-02-13 04:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='base_charateristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'attack': 0, 'defense': 0, 'knowledge': 0, 'spell_power': 0}),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_spells',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='has_spellbook',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='town',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
