# Generated by Django 2.1.5 on 2019-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190213_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='portrait',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
