# Generated by Django 2.1.5 on 2019-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190213_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='has_spellbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='portrait',
            field=models.FileField(upload_to=''),
        ),
    ]
