# Generated by Django 2.1.5 on 2019-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190213_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Hero'),
        ),
    ]
