# Generated by Django 2.1.5 on 2019-02-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hero',
        ),
    ]
